import doc from 'pdfkit';
import PDFDocument from 'pdfkit' ;

export const generatePdf = async (data)=>{
    return new Promise((resolve,reject)=>{
        const doc = new PDFDocument({
            size:"A4",
            margin:50,
            info:{
                Author:"Unified - Ai Workspace",
                Title:data.title,
                Creator:"Unified-Ai"
            }
        })

    
    // here the doc or pdf is generated in the form of chunks we will store them in the array
    // and then buffer is then concatenate

    const chunks = []
    // store in chunk
    doc.on("data",(chunk)=>{chunks.push(chunk)})
    // concatenate all the chunk  
    doc.on("end",()=> resolve(Buffer.concat(chunks)))

    // any error while createing doc
    doc.on("error",()=>reject)

    // which and what data to add in chunk

    // title
    doc
        .fontSize(28)
        .text(data.title,{

        })
        .fillColor("#111827")

        if(data.subtitle){
            doc.moveDown(0.5)
        }
        // subtitle

    doc
        .fontSize(12)
        .text(data.subtitle,{
            align:"center"
        })
        .fillColor("#6B7280")

    doc.moveDown(2)

    data?.sections.forEach(s => {
            doc
        .fontSize(18)
        .text(s.heading,{
           
        })
        .fillColor("#111827")
        
        doc.moveDown(0.5)

        s?.points.forEach(p=>{
             doc
            .fontSize(12)
            .text("• "+p,{
                lineGap:5
            })
            .fillColor("#374151")
        })
        doc.moveDown()
    });

    // footer
    doc.moveDown()

    doc
            .fontSize(12)
            .text("Generated By unified-Ai",{
                align:"center"
            })
            .fillColor("#9CA3AF")


            doc.end()

    })

}